
#FROM tiangolo/meinheld-gunicorn-flask:python3.8

FROM tiangolo/uwsgi-nginx-flask:python3.8

RUN apt update
RUN apt install -y libc-dev mariadb-client libmariadb-dev liblapack-dev libopenblas-dev
ENV STATIC_URL /static
ENV STATIC_PATH /var/www/app/static

COPY requirements.txt /var/www/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /var/www/requirements.txt
